# Generated by Django 3.0.4 on 2020-03-21 19:44

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(null=True, upload_to=listings.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
