# Generated by Django 3.0.4 on 2020-03-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.TextField(default='main'),
        ),
    ]
