# Generated by Django 3.0.5 on 2020-04-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='user_owner',
            new_name='checkout_user',
        ),
        migrations.AddField(
            model_name='cartentry',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
